<?php

declare(strict_types=1);

use RoundlyConsulting\Advertisements\Models\Advertisement;
use RoundlyConsulting\Advertisements\Models\AdvertisementEvent;
use RoundlyConsulting\Advertisements\Models\Category;
use RoundlyConsulting\Advertisements\Models\Placement;

return [

    /*
    |--------------------------------------------------------------------------
    | Advertisement Model
    |--------------------------------------------------------------------------
    |
    | The Eloquent model used to store advertisements. Override this with your
    | own class (extending the package model) to customise behaviour.
    |
    */

    'model' => Advertisement::class,

    /*
    |--------------------------------------------------------------------------
    | Key Type
    |--------------------------------------------------------------------------
    |
    | The key type used for the polymorphic author column. Use "uuid" or "ulid"
    | when the models that author advertisements use UUID/ULID primary keys,
    | otherwise leave it as "bigint". Anything unrecognized falls back to
    | "bigint". Your author models must share one key type — set this to match.
    |
    | Supported: "bigint", "uuid", "ulid"
    |
    */

    'key_type' => env('ADVERTISEMENTS_KEY_TYPE', 'bigint'),

    /*
    |--------------------------------------------------------------------------
    | Placement Model
    |--------------------------------------------------------------------------
    |
    | The Eloquent model used to store placements (zones where an ad renders).
    | Override with your own class extending the package model.
    |
    */

    'placement_model' => Placement::class,

    /*
    |--------------------------------------------------------------------------
    | Category Model
    |--------------------------------------------------------------------------
    |
    | The Eloquent model used to store advertisement categories. Override with
    | your own class extending the package model.
    |
    */

    'category_model' => Category::class,

    /*
    |--------------------------------------------------------------------------
    | Advertisement Event Model
    |--------------------------------------------------------------------------
    |
    | The Eloquent model used to store impression and click events. Override with
    | your own class extending the package model.
    |
    */

    'event_model' => AdvertisementEvent::class,

    /*
    |--------------------------------------------------------------------------
    | Tracking
    |--------------------------------------------------------------------------
    |
    | Impression and click recording. When "buffered" is true, recording is
    | dispatched to the queue (on the optional connection/queue) instead of being
    | written inline — useful to smooth high write volume.
    |
    */

    'tracking' => [
        'buffered' => env('ADVERTISEMENTS_TRACKING_BUFFERED', false),
        'queue' => env('ADVERTISEMENTS_TRACKING_QUEUE'),
        'connection' => env('ADVERTISEMENTS_TRACKING_CONNECTION'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Fallback Locale
    |--------------------------------------------------------------------------
    |
    | Locale used when the active locale has no translation for a translatable
    | attribute (name, description, slug). Defaults to the app fallback locale.
    |
    */

    'fallback_locale' => env('ADVERTISEMENTS_FALLBACK_LOCALE', config('app.fallback_locale', 'en')),

    /*
    |--------------------------------------------------------------------------
    | Slugs
    |--------------------------------------------------------------------------
    |
    | Slugs are generated by roundly-consulting/sluggable-for-laravel. With
    | "history" on, every retired advertisement slug is kept and a request for
    | it redirects (301) to the current one. Publish and run sluggable's
    | migration ("sluggable-migrations") before switching it on.
    |
    */

    'slugs' => [
        'history' => env('ADVERTISEMENTS_SLUG_HISTORY', false),
    ],

    /*
    |--------------------------------------------------------------------------
    | Default Currency
    |--------------------------------------------------------------------------
    |
    | ISO 4217 currency code used when a price is supplied as a bare amount
    | (e.g. via AdvertisementData::fromAmount()) without an explicit currency.
    |
    */

    'default_currency' => env('ADVERTISEMENTS_CURRENCY', 'EUR'),

    /*
    |--------------------------------------------------------------------------
    | Facade Alias
    |--------------------------------------------------------------------------
    |
    | Register the `Advertisements` facade alias automatically so you can call
    | it without importing the fully-qualified class. Set to false to opt out.
    |
    */

    'register_facade_alias' => (bool) env('ADVERTISEMENTS_FACADE_ALIAS', true),

    /*
    |--------------------------------------------------------------------------
    | Media (creatives)
    |--------------------------------------------------------------------------
    |
    | Visual creatives are stored through roundly-consulting/media-library-for-laravel.
    | Each placement gets its own single-file bucket named "{prefix}:{placement-slug}"
    | with a "display" variant fit to that placement's width x height. A generic,
    | size-less "{fallback_bucket}" bucket is tried before falling back to a text ad.
    |
    */

    'media' => [
        'creative_bucket_prefix' => 'creative',
        'fallback_bucket' => 'creative',
        'disk' => env('ADVERTISEMENTS_MEDIA_DISK'),
        'responsive_widths' => null,
        'display_variant' => 'display',
        'use_fallback_bucket' => true,
        'text_ad_view' => 'advertisements::text-ad',
    ],

    /*
    |--------------------------------------------------------------------------
    | Geo (targeting & reporting)
    |--------------------------------------------------------------------------
    |
    | Location awareness is powered by roundly-consulting/geolocation-for-laravel.
    | Targeting filters the active-ads query to the viewer's resolved location, and
    | impression/click recording stamps the viewer's country (indexed) plus
    | region/city/coords (in the event meta) for per-country reporting.
    |
    | "match_when_unknown" controls serving when the viewer location cannot be
    | resolved: "untargeted_only" serves only ads with no targeting, "all" serves
    | every active ad regardless of targeting.
    |
    */

    'geo' => [
        'targeting_enabled' => env('ADVERTISEMENTS_GEO_TARGETING', true),
        'untargeted_match' => true,
        'match_when_unknown' => 'untargeted_only',
        'stamp_events' => env('ADVERTISEMENTS_GEO_STAMP', true),
    ],

];
